version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_evenements
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  php:
    build: ./php
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./project:/var/www/html
      - ./nginx/ssl:/etc/ssl/certs
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
